#!/bin/ash
sed -i 's%^XENDOMAINS_SAVE=.*%XENDOMAINS_SAVE=%' /etc/default/xendomains
sed -i "/\/v$(cut -d. -f-2 \/etc\/alpine-release)\/community$/s%^#%%" /etc/apk/repositories
apk -U add multipath-tools nano screen util-linux udev zfs || exit 1
setup-udev
#grep -q '^\tfilter = ' /etc/lvm/lvm.conf || \
#	sed -i '/# filter = \[ "a|\.\*\/|" \]/a \\tfilter = [ "a|^/dev/sd.*|", "r/.*/" ]' /etc/lvm/lvm.conf
#sed -i 's%^\twrite_cache_state = 1$%\twrite_cache_state = 0%' /etc/lvm/lvm.conf
#modprobe multipath
lbu inc /etc/xen
#lbu inc /root/.ssh
#rc-update add lvm boot
rc-update add xendomains default
lbu ci
apk upgrade
echo 'Stage #3: All done!'
