#!/bin/ash

dd bs=1M if=/dev/zero of=/dev/sda count=5

cat > answers <<EOF
# Example answer file for setup-alpine script
# If you don't want to use a certain option, then comment it out

# Use US layout with US variant
KEYMAPOPTS="us us"

# Set hostname to alpine-test
HOSTNAMEOPTS="-n ovpn-stage"

# Contents of /etc/network/interfaces
INTERFACESOPTS="auto lo
iface lo inet loopback

auto eth0
iface eth0 inet static
	hostname ovpn-stage
	address 10.118.133.133
	netmask 255.255.252.0
	gateway 10.118.132.1
"

# Search domain of example.com, Google public nameserver
DNSOPTS="-d krit.pro 10.118.131.100 10.118.145.13"

# Set timezone to UTC
TIMEZONEOPTS="-z Europe/Samara"

# set http/ftp proxy
PROXYOPTS="none"

# Add a random mirror
APKREPOSOPTS="http://mirror.yandex.ru/mirrors/alpine/v3.13/main
#http://mirror.yandex.ru/mirrors/alpine/v3.13/community
#http://mirror.yandex.ru/mirrors/alpine/edge/main
#http://mirror.yandex.ru/mirrors/alpine/edge/community
#http://mirror.yandex.ru/mirrors/alpine/edge/testing
"

# Install Openssh
SSHDOPTS="-c openssh"

# Use openntpd
NTPOPTS="-c openntpd"

# Use /dev/sda as a data disk
DISKOPTS="-m data none"

# Setup in /media/sdb1
LBUOPTS="/media/sda1"
APKCACHEOPTS="/media/sda1/cache"
EOF
mkdir -p /media/target
setup-alpine -f answers

apk add e2fsprogs syslinux sfdisk || exit 1

sfdisk /dev/sda <<EOF
label: dos
label-id: 0x00000000
device: /dev/sda
unit: sectors
sector-size: 512

/dev/sda1 : start=          32, size=     10240, type=c, bootable
EOF
#/dev/sda1 : start=          32, size=     4194304, type=83, bootable
#EOF
#mkfs.ext3 -F /dev/sda1 || exit 2
mkdosfs -F32 /dev/sda1 || exit 2
dd if=/usr/share/syslinux/mbr.bin of=/dev/sda conv=notrunc
syslinux /dev/sda1

mount -t vfat /dev/sda1 /media/target || exit 3
cdrom="$(df | grep /media/ | head -n1 | awk \{print\ \$6\})"
cp -a $cdrom/.alpine-release $cdrom/* /media/target
umount /media/target
echo 'All done!'
