#!/bin/ash
if [ "$1" ]; then
  dev="$1"
else
  echo "Please input target block device. [sda]"
  read dev
fi
PARTPREFIX=1
#PARTPREFIX=p1
dev=${dev:-sda}
echo "Setup into device: $dev"
echo "root:abc" | chpasswd

#dd bs=1M if=/dev/zero of=/dev/$dev count=5
apk add sgdisk
sgdisk --zap-all /dev/$dev
mdev -s
if=$(ip a|awk -F:\  \{print\ \$2\}|sed /^$/d|grep -v lo|head -n1)
#if={if:-eth0}

cat > answers <<EOF
# Example answer file for setup-alpine script
# If you don't want to use a certain option, then comment it out

# Use US layout with US variant
KEYMAPOPTS="us us"

# Set hostname to alpine-test
HOSTNAMEOPTS="-n stage1"

# Set device manager to mdev
DEVDOPTS="mdev"

# Contents of /etc/network/interfaces
INTERFACESOPTS="# The loopback network interface
auto lo
iface lo inet loopback

auto $if
iface $if inet dhcp
"
#iface $if inet static
#	hostname stage1
#	address 10.118.133.133/22
#	gateway 10.118.132.1
#"

# Search domain of example.com, Google public nameserver
DNSOPTS="-d local  8.8.4.4  8.8.8.8"
#DNSOPTS="-d krit.pro 10.118.131.100 10.118.145.13"

# Set timezone to UTC
TIMEZONEOPTS="-z Europe/Samara"

# set http/ftp proxy
PROXYOPTS="none"

# Add a random mirror
APKREPOSOPTS="http://mirror.yandex.ru/mirrors/alpine/v$(cut -d. -f-2 /etc/alpine-release)/main
http://mirror.yandex.ru/mirrors/alpine/v$(cut -d. -f-2 /etc/alpine-release)/community
#http://mirror.yandex.ru/mirrors/alpine/edge/main
#http://mirror.yandex.ru/mirrors/alpine/edge/community
#http://mirror.yandex.ru/mirrors/alpine/edge/testing
"

# Install Openssh
SSHDOPTS="-c openssh"

# Use openntpd
NTPOPTS="-c chrony"

# Use /dev/sda as a data disk
DISKOPTS="-m data none"

# Setup in /media/sdb1
LBUOPTS="/media/${dev}${PARTPREFIX}"
APKCACHEOPTS="/media/${dev}${PARTPREFIX}/cache"
EOF
mkdir -p /media/target
setup-alpine -f answers

apk add e2fsprogs syslinux sfdisk || exit 1

sfdisk /dev/$dev <<EOF
label: dos
label-id: 0x00000000
device: /dev/none
unit: sectors
sector-size: 512

#2GB vfat
#/dev/none : start=          32, size=     4194304, type=c, bootable

#1GB ext3
#/dev/none : start=          32, size=     2097152, type=83, bootable
/dev/none : start=          32, size=     2097120, type=83, bootable

#2GB ext3
#/dev/none : start=          32, size=     4194304, type=83, bootable

#3GB ext3
#/dev/none : start=          32, size=     6291456, type=83, bootable

#9GB ext3
#/dev/none : start=          32, size=     18874368, type=83, bootable
EOF

mkfs.ext3 -F /dev/${dev}${PARTPREFIX} || exit 2
#mkdosfs -F32 /dev/${dev}${PARTPREFIX} || exit 2

dd if=/usr/share/syslinux/mbr.bin of=/dev/$dev conv=notrunc
mdev -s
# Only for vfat need.
#syslinux /dev/${dev}${PARTPREFIX}

mount -t ext3 /dev/${dev}${PARTPREFIX} /media/target || exit 3
#mount -t vfat /dev/${dev}${PARTPREFIX} /media/target || exit 3

# Only for ext3 need.
extlinux --install /media/target || extlinux --update /media/target || exit 4

cdrom="$(df | grep /media/ | head -n1 | awk \{print\ \$6\})"
#cp -a $cdrom/.alpine-release $cdrom/* "$(dirname "$0")/" /media/target
cp -a $cdrom/.alpine-release $cdrom/* "/root/a1" /media/target
umount /media/target

echo 'Stage #1: All done! Need reboot and run next stage #2.'
