#!/bin/ash
sed -i '/\/v.*\/community$/s%^#%%' /etc/apk/repositories
apk -U add docker docker-compose e2fsprogs-extra gptfdisk cfdisk lvm2 thin-provisioning-tools bridge bridge-utils nano screen qemu-guest-agent || exit 1
#df /var/lib/docker >/dev/null || exit 2
#apk -U add docker docker-compose || exit 3

rc-update add docker boot
mkdir -p /etc/docker
cat > /etc/docker/daemon.json <<EOF
{
  "log-driver": "json-file",
  "log-opts": {"max-size": "2m", "max-file": "3"}
}
EOF
service docker start

rc-update add local
cat > /etc/local.d/lbu.stop <<EOF
#!/bin/ash
lbu ci
exit 0
EOF
chmod +x /etc/local.d/lbu.stop
service local start

lbu inc /root/.ssh
lbu inc /var/lib/docker

rc-update add lvm boot

lbu ci
apk -U upgrade
echo 'Stage #3: All done!'
